//! Reading the file users are handed.
//!
//! The profile below is the one `synology_vpn` actually renders — its
//! `CLIENT_TEMPLATE` in `ansible/synology/roles/synology_vpn/files/apply_vpn.py`,
//! filled in with e4e-nas's own values from `spec/e4e-nas/vpn.yml`. Testing
//! against a profile I invented would only prove the parser agrees with my
//! idea of one.
//!
//! The `<ca>` and `<tls-auth>` bodies are stand-ins: what matters about them
//! here is where they sit and how they are delimited, and a real key in a
//! repository is a real key in a repository.

use synology_filestation_openvpn::{Error, KeyDirection, Profile};

const TA_KEY_HEX: &str = concat!(
    "95300e5e0e76a0ed8f58bcdea1b9475b53e468c00d3ba0fb3400e40b2d22ea32",
    "bc5f2f826ebf6378648286697501db24bf2696fa4597231db5b680f6c2e04495",
    "24116f6ea79ae602988d7cf021d8fd35829ddb0249ca4e265723bd93c8141c31",
    "1c2c4bdd4142d7ac06eac732903ed85e547ea8af3c4c04149a4a48e3f31b4bb4",
    "9d73ec8c5da92958a44a23b1e978b4ea0c91b915d650975ede0e784c54544c2f",
    "3947bd3deb19a49925ae2e8b0675d79c77d31116502426e0d740ec23d1d9a634",
    "ba08b32b4ad94b5e5f5eda002e07120ef092c3b08f4bc0842de9ebb0dc953dad",
    "59a382aeb73f10a3b3a75277d045906b48e82f6d5aba62017fc218180fdb4ae6",
);

fn key_body() -> String {
    TA_KEY_HEX
        .as_bytes()
        .chunks(32)
        .map(|line| std::str::from_utf8(line).expect("hex is ascii"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// What a user downloads from the `installers` share.
fn published_profile() -> String {
    format!(
        "\
# OpenVPN client config for e4e-nas.ucsd.edu — generated by synology_vpn, do not hand-edit.
#
# Import into your OpenVPN client, then mount SMB from 10.90.24.1:
#   macOS/Linux:  smb://10.90.24.1/<share>
# Log in with your KRG.LOCAL (AD) username and password.
client
dev tun
proto udp
remote e4e-nas.ucsd.edu 1194
resolv-retry infinite
nobind
persist-key
persist-tun
auth-user-pass
# Split tunnel: do NOT route all traffic through the NAS.
cipher AES-256-CBC
auth SHA512
remote-cert-tls server
verify-x509-name e4e-nas.ucsd.edu name
verb 3
<ca>
-----BEGIN CERTIFICATE-----
a chain would be here
-----END CERTIFICATE-----
</ca>
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
{}
-----END OpenVPN Static key V1-----
</tls-auth>
",
        key_body()
    )
}

#[test]
fn the_published_profile_reads() {
    let profile = Profile::parse(&published_profile()).expect("the file users are given");

    assert_eq!(profile.remote, "e4e-nas.ucsd.edu");
    assert_eq!(profile.port, 1194);
    assert_eq!(profile.server_name, "e4e-nas.ucsd.edu");
    assert_eq!(
        profile.key_direction,
        KeyDirection::Inverse,
        "the client signs with slot one; the server holds slot zero"
    );
    assert!(profile.static_key.is_some(), "the tls-auth key is embedded");
    assert!(profile.ca_pem.contains("BEGIN CERTIFICATE"));
    assert!(
        profile.wants_credentials,
        "the NAS authenticates a username and password"
    );
}

#[test]
fn the_certificate_block_stops_where_it_closes() {
    // The `<ca>` block is followed by `key-direction` and then another block.
    // A parser that ran past the closing tag would swallow the key direction
    // and the static key with it.
    let profile = Profile::parse(&published_profile()).expect("valid");

    assert!(!profile.ca_pem.contains("key-direction"));
    assert!(!profile.ca_pem.contains("OpenVPN Static key"));
    assert!(profile.ca_pem.trim().ends_with("-----END CERTIFICATE-----"));
}

#[test]
fn directives_inside_a_block_are_not_directives() {
    // A certificate body is base64 and a key body is hex, and either can begin
    // with a word that looks like an option. Reading the contents of a block
    // as configuration is how a parser ends up refusing a perfectly good file.
    let profile = Profile::parse(
        "\
remote e4e-nas.ucsd.edu 1194
<ca>
proto tcp
compress lz4
-----END CERTIFICATE-----
</ca>
",
    )
    .expect("what is inside a block stays inside it");

    assert_eq!(profile.remote, "e4e-nas.ucsd.edu");
}

#[test]
fn a_profile_asking_for_tcp_is_refused() {
    // A different framing entirely. Connecting anyway produces a tunnel that
    // comes up and moves nothing.
    let text = published_profile().replace("proto udp", "proto tcp");

    assert!(matches!(
        Profile::parse(&text),
        Err(Error::UnsupportedProfileOption(_))
    ));
}

#[test]
fn a_profile_asking_for_compression_is_refused() {
    let text = published_profile().replace("verb 3", "comp-lzo");

    assert!(matches!(
        Profile::parse(&text),
        Err(Error::UnsupportedCompression(_))
    ));
}

#[test]
fn a_profile_saying_compression_is_off_is_fine() {
    let text = published_profile().replace("verb 3", "comp-lzo no");

    assert!(Profile::parse(&text).is_ok());
}

#[test]
fn a_profile_asking_for_a_client_certificate_says_so_early() {
    // This client has no certificate to offer. Failing here names the reason;
    // failing inside a TLS handshake does not.
    let text = published_profile().replace("verb 3", "cert client.crt");

    assert!(matches!(
        Profile::parse(&text),
        Err(Error::UnsupportedProfileOption(_))
    ));
}

#[test]
fn a_profile_naming_a_cipher_we_cannot_speak_is_refused() {
    let text = published_profile().replace("cipher AES-256-CBC", "cipher AES-256-GCM");

    assert!(matches!(
        Profile::parse(&text),
        Err(Error::UnsupportedCipher(_))
    ));
}

#[test]
fn a_profile_with_no_remote_is_not_a_profile() {
    let text = published_profile().replace("remote e4e-nas.ucsd.edu 1194", "");

    assert!(matches!(Profile::parse(&text), Err(Error::BadProfile(_))));
}

#[test]
fn a_profile_with_no_trust_anchor_is_refused() {
    // Without the chain there is nothing to check the server against, and the
    // system store is deliberately not a fallback: the certificate is publicly
    // issued, so trusting every public CA would trust anyone who can obtain
    // one for that name.
    let text = published_profile();
    let without = text
        .split_once("<ca>")
        .map(|(before, _)| before.to_string())
        .expect("the block is there");

    assert!(matches!(
        Profile::parse(&without),
        Err(Error::BadProfile(_))
    ));
}

#[test]
fn a_remote_without_a_port_gets_the_default() {
    let text =
        published_profile().replace("remote e4e-nas.ucsd.edu 1194", "remote e4e-nas.ucsd.edu");

    assert_eq!(Profile::parse(&text).expect("valid").port, 1194);
}

#[test]
fn a_profile_becomes_a_session_configuration() {
    let profile = Profile::parse(&published_profile()).expect("valid");
    let credentials = synology_filestation_openvpn::credentials("ad-user", "hunter2");

    let config = profile
        .into_config(Some(credentials))
        .expect("everything a session needs is in the file");

    assert_eq!(config.server_name, "e4e-nas.ucsd.edu");
    assert_eq!(config.key_direction, KeyDirection::Inverse);
    assert!(config.credentials.is_some());
    assert!(
        config.client_auth.is_none(),
        "the NAS asks for no client certificate"
    );
}

#[test]
fn a_remote_may_name_its_protocol_as_well_as_its_port() {
    // `remote host port proto` is the third form OpenVPN writes, and it used
    // to match no arm at all — so a perfectly ordinary profile failed with
    // "no remote", which is true and tells the user nothing.
    let text = published_profile().replace(
        "remote e4e-nas.ucsd.edu 1194",
        "remote e4e-nas.ucsd.edu 1194 udp",
    );

    let profile = Profile::parse(&text).expect("a remote with its protocol spelled out");
    assert_eq!(profile.remote, "e4e-nas.ucsd.edu");
    assert_eq!(profile.port, 1194);
}

#[test]
fn a_remote_naming_tcp_is_refused_like_any_other_tcp_profile() {
    let text = published_profile().replace(
        "remote e4e-nas.ucsd.edu 1194",
        "remote e4e-nas.ucsd.edu 1194 tcp",
    );

    assert!(matches!(
        Profile::parse(&text),
        Err(Error::UnsupportedProfileOption(_))
    ));
}

#[test]
fn udp_pinned_to_one_address_family_is_still_udp() {
    // `udp4` and `udp6` say which family to resolve to, not which transport to
    // speak. Refusing them as an unsupported protocol refuses a file we can
    // carry out perfectly well.
    for spelling in ["udp4", "udp6"] {
        let text = published_profile().replace("proto udp", &format!("proto {spelling}"));
        assert!(
            Profile::parse(&text).is_ok(),
            "{spelling} is a family, not a transport"
        );
    }
}

#[test]
fn a_cipher_list_only_has_to_contain_one_we_speak() {
    // `data-ciphers` is a colon-separated list of what the client will accept,
    // and the standard one leads with the AEAD ciphers. Compared whole against
    // a single name it matches nothing, so the profile is refused for offering
    // us more choices than we needed.
    let text = published_profile().replace(
        "cipher AES-256-CBC",
        "data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC",
    );

    assert!(Profile::parse(&text).is_ok(), "AES-256-CBC is on the list");
}

#[test]
fn a_cipher_list_with_nothing_we_speak_is_still_refused() {
    let text = published_profile().replace(
        "cipher AES-256-CBC",
        "data-ciphers AES-256-GCM:CHACHA20-POLY1305",
    );

    assert!(matches!(
        Profile::parse(&text),
        Err(Error::UnsupportedCipher(_))
    ));
}

#[test]
fn credentials_kept_in_a_file_are_still_credentials() {
    // `auth-user-pass <file>` asks for the same thing as the bare form. Read
    // as "no credentials wanted", the session sends two empty fields and the
    // server answers `AUTH_FAILED` — a password problem that is not one.
    let text = published_profile().replace("auth-user-pass", "auth-user-pass credentials.txt");

    assert!(
        Profile::parse(&text).expect("valid").wants_credentials,
        "the file is where they are, not whether they are wanted"
    );
}
